/** First-line 5-step flow copy (merged into i18n STR). */
export const FL5_STR = {
  en: {
    fl5_over_listen: "STEP 1 · LISTEN",
    fl5_over_understand: "STEP 2 · VOCABULARY",
    fl5_over_repeat: "STEP 3 · REPEAT",
    fl5_over_recall: "STEP 4 · RECALL",
    fl5_over_swap: "STEP 5 · SWAP",
    fl5_hero_today: "Today's sentence",
    fl5_btn_listen: "Listen",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Listen slowly",
    fl5_next_vocab: "Learn the words",
    fl5_situation_when: "When do you use this?",
    fl5_words_hint: "Tap a word to hear it",
    fl5_repeat_hint: "Repeat what you hear",
    fl5_btn_listen_again: "Listen again",
    fl5_btn_speak_now: "Speak now",
    fl5_btn_speaking: "Listening…",
    fl5_btn_follow_speak: "Tap to speak",
    fl5_btn_follow_speaking: "Repeating…",
    fl5_next_repeat: "Say the sentence",
    fl5_next_recall: "Now say it yourself",
    fl5_recall_hint: "The sentence is hidden. Say it from memory!",
    fl5_recall_line1: "The sentence is hidden.",
    fl5_recall_line2: "Say it from memory!",
    fl5_roman_hint: "Pronunciation hint",
    fl5_btn_speak_practice: "Tap to speak",
    fl5_next_swap: "Make it yours",
    fl5_next_result: "See my result",
    fl5_you_said: "What you said",
    fl5_swap_pick: "Pick a word to make your sentence",
    fl5_swap_mini: "My sentence",
    fl5_btn_speak_swap: "Speak like this",
    fl5_btn_listen_swap: "Listen like this",
    fl5_spoken_count: "{n} / 3 times spoken",
    fl5_over_done: "STEP 5 · DONE",
    fl5_badge_first_done: "You did it! 🎉",
    fl5_result_title: "You did it! 🎉",
    fl5_rs_you_said: "What I said",
    fl5_rs_model: "Model answer",
    fl5_apply_section: "You can also say...",
    fl5_apply_hint: "Try replacing the blank with these words:",
    fl5_rs_vocab: "Vocabulary",
    fl5_stat_times: "Times spoken",
    fl5_stat_streak: "Day streak",
    fl5_btn_next_day: "Start Day {n} →",
    fl5_btn_retry_swap: "Try again",
    fl5_btn_home_go: "Go to home",
    fl5_rs_eval_perfect: "Perfect!",
    fl5_rs_eval_good: "Good try!",
    fl5_rs_eval_keep: "Keep going!",
    fl5_day_done_title: "Day {n} complete!",
    fl5_day_done_sub: "You spoke Korean today",
    fl5_recall_hidden: "Sentence hidden — use the pronunciation hint.",
    fl5_btn_retry_speak: "Tap to speak again",
    fl5_btn_mic_prepare: "Get ready...",
    fl5_btn_mic_listening: "Listening...",
    fl5_mic_hint_idle_repeat: "Tap the button and speak the sentence above",
    fl5_mic_hint_idle_recall: "Tap the button and speak from memory",
    fl5_mic_hint_listening: "Keep speaking... I'm listening 👂",
    fl5_mic_hint_done: "Done! Tap next when ready",
    fl5_stt_empty: "We couldn't catch that. Try again!",
    fl5_onboard_step: "Step {n} of 3",
    fl5_onboard_1: "First, listen to the sentence 3 times. Tap the Listen button!",
    fl5_onboard_2: "Tap each word to hear how it sounds.",
    fl5_onboard_3: "Now tap 'Tap to speak' and say the sentence out loud!",
    fl5_onboard_cta: "Got it →",
    fl5_onboard_start: "Let's start!",
    fl_pre_tooltip_step: "Step {n} of 3",
    fl_pre_tooltip_1: "Listen to the sentence 3 times before speaking",
    fl_pre_tooltip_2: "Tap each word to hear how it sounds",
    fl_pre_tooltip_3: "Tap 'Tap to speak' and say the sentence out loud!",
    fl_pre_tooltip_start: "Let's start! →",
    fl_browser_not_supported_title: "Voice not available in this browser",
    fl_browser_not_supported_desc: "Please open Kkobi in Chrome for the full speaking experience.",
    fl_open_in_chrome: "Open in Chrome",
    fl_browser_not_supported_hint: "Copy the link and paste it in Chrome if the button doesn't work.",
    fl_mic_permission_title: "Microphone access denied",
    fl_mic_permission_desc: "Please allow microphone access in your browser settings and try again.",
    fl_stt_try_again: "Try again",
    fl_stt_no_speech_hint: "We didn't hear anything. Speak clearly and try again!",
    fl_stt_network_error_hint: "Network error. Please check your connection and try again.",
    fl_stt_generic_error: "Voice input had a problem. Please try again.",
    fl_chrome_recommended: "For best experience, open in Chrome browser.",
    fl_stt_try_anyway: "Try speaking anyway"
  },
  ko: {
    fl5_over_listen: "STEP 1 · 듣기",
    fl5_over_understand: "STEP 2 · 단어",
    fl5_over_repeat: "STEP 3 · 따라 말하기",
    fl5_over_recall: "STEP 4 · 떠올리기",
    fl5_over_swap: "STEP 5 · 바꿔 말하기",
    fl5_hero_today: "오늘의 문장",
    fl5_btn_listen: "듣기",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "천천히 듣기",
    fl5_next_vocab: "단어 배우기",
    fl5_situation_when: "언제 써요?",
    fl5_words_hint: "단어 탭하면 발음 들려요",
    fl5_repeat_hint: "방금 들은 대로 따라 말해봐요",
    fl5_btn_listen_again: "다시 듣기",
    fl5_btn_speak_now: "지금 말하기",
    fl5_btn_speaking: "듣는 중…",
    fl5_btn_follow_speak: "탭해서 말하기",
    fl5_btn_follow_speaking: "따라 말하는 중…",
    fl5_next_repeat: "문장 말하기",
    fl5_next_recall: "이제 스스로 말하기",
    fl5_recall_hint: "문장은 숨겨져 있어요. 머리로 떠올려요!",
    fl5_recall_line1: "문장 숨김 상태예요.",
    fl5_recall_line2: "외운 대로 말해봐요!",
    fl5_roman_hint: "발음 힌트",
    fl5_btn_speak_practice: "탭해서 말하기",
    fl5_next_swap: "나만의 문장으로",
    fl5_next_result: "내 결과 보기",
    fl5_you_said: "방금 내가 한 말",
    fl5_swap_pick: "넣고 싶은 단어 고르기",
    fl5_swap_mini: "내 문장",
    fl5_btn_speak_swap: "이렇게 말하기",
    fl5_btn_listen_swap: "이렇게 듣기",
    fl5_spoken_count: "{n} / 3번 말함",
    fl5_over_done: "STEP 5 · 완료",
    fl5_badge_first_done: "해냈어요! 🎉",
    fl5_result_title: "잘했다! 🎉",
    fl5_rs_you_said: "내가 말한 거",
    fl5_rs_model: "모범 답",
    fl5_apply_section: "이렇게도 말할 수 있어요…",
    fl5_apply_hint: "빈칸에 아래 단어 넣어봐요:",
    fl5_rs_vocab: "단어장",
    fl5_stat_times: "말한 횟수",
    fl5_stat_streak: "연속 일수",
    fl5_btn_next_day: "Day {n} 시작하기 →",
    fl5_btn_retry_swap: "다시 해보기",
    fl5_btn_home_go: "홈으로",
    fl5_rs_eval_perfect: "완전 딱이에요!",
    fl5_rs_eval_good: "좋았어요!",
    fl5_rs_eval_keep: "한 번 더 가보자!",
    fl5_day_done_title: "Day {n} 끝!",
    fl5_day_done_sub: "오늘도 한국어 말했어요",
    fl5_recall_hidden: "문장 안 보임 — 발음 힌트 쓰면 돼요.",
    fl5_btn_retry_speak: "탭해서 다시 말하기",
    fl5_btn_mic_prepare: "준비…",
    fl5_btn_mic_listening: "듣고 있어요…",
    fl5_mic_hint_idle_repeat: "버튼 누르고 위 문장 말하기",
    fl5_mic_hint_idle_recall: "버튼 누르고 외운 대로 말하기",
    fl5_mic_hint_listening: "계속 말해요… 듣고 있어요 👂",
    fl5_mic_hint_done: "끝! 준비되면 다음으로",
    fl5_stt_empty: "목소리가 안 잡혔어요. 한 번 더!",
    fl5_onboard_step: "3단계 중 {n}단계",
    fl5_onboard_1: "먼저 문장을 3번 들어요. 듣기 버튼!",
    fl5_onboard_2: "단어 하나씩 탭하면 소리 들려요.",
    fl5_onboard_3: "이제 「탭해서 말하기」로 크게 따라 말해봐요!",
    fl5_onboard_cta: "오케이 →",
    fl5_onboard_start: "시작해요!",
    fl_pre_tooltip_step: "3단계 중 {n}단계",
    fl_pre_tooltip_1: "말하기 전에 문장을 3번 들어요",
    fl_pre_tooltip_2: "단어 탭하면 발음 확인",
    fl_pre_tooltip_3: "「탭해서 말하기」 눌러 따라 말하기!",
    fl_pre_tooltip_start: "레츠고! →",
    fl_browser_not_supported_title: "이 브라우저에선 목소리 연습 제한 있어요",
    fl_browser_not_supported_desc: "크롬으로 Kkobi 열면 말하기 풀로 써요.",
    fl_open_in_chrome: "Chrome에서 열기",
    fl_browser_not_supported_hint: "버튼 안 되면 주소 복사해서 Chrome에 붙여 넣어요.",
    fl_mic_permission_title: "마이크 권한이 막혀 있어요",
    fl_mic_permission_desc: "브라우저 설정에서 마이크 허용 후 다시 시도해 주세요.",
    fl_stt_try_again: "다시 시도",
    fl_stt_no_speech_hint: "소리가 안 들려요. 조금 크게 또렷하게 말해봐요!",
    fl_stt_network_error_hint: "네트워크 오류예요. 연결 확인 후 다시요.",
    fl_stt_generic_error: "음성 입력 문제가 있어요. 한 번 더요.",
    fl_chrome_recommended: "가장 매끄러운 건 Chrome이에요.",
    fl_stt_try_anyway: "그래도 말해볼래요"
  },
  id: {
    fl5_over_listen: "STEP 1 · DENGAR",
    fl5_over_understand: "STEP 2 · KOSAKATA",
    fl5_over_repeat: "STEP 3 · ULANG",
    fl5_over_recall: "STEP 4 · UCAP SENDIRI",
    fl5_over_swap: "STEP 5 · UBAH",
    fl5_hero_today: "Kalimat hari ini",
    fl5_btn_listen: "Dengarkan",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Dengarkan perlahan",
    fl5_next_vocab: "Pelajari katanya",
    fl5_situation_when: "Kapan dipakai?",
    fl5_words_hint: "Ketuk kata untuk mendengar",
    fl5_repeat_hint: "Ulangi apa yang kamu dengar",
    fl5_btn_listen_again: "Dengarkan lagi",
    fl5_btn_speak_now: "Bicara sekarang",
    fl5_btn_speaking: "Mendengarkan…",
    fl5_btn_follow_speak: "Ketuk untuk bicara",
    fl5_btn_follow_speaking: "Sedang menirukan…",
    fl5_next_repeat: "Ucapkan kalimatnya",
    fl5_next_recall: "Sekarang ucapkan sendiri",
    fl5_recall_hint: "Kalimat disembunyikan. Ucapkan dari ingatan!",
    fl5_recall_line1: "Kalimat disembunyikan.",
    fl5_recall_line2: "Ucapkan dari ingatan!",
    fl5_roman_hint: "Petunjuk pelafalan",
    fl5_btn_speak_practice: "Ketuk untuk bicara",
    fl5_next_swap: "Ubah kalimatmu",
    fl5_next_result: "Lihat hasil saya",
    fl5_you_said: "Yang kamu katakan",
    fl5_swap_pick: "Pilih kata untuk kalimatmu",
    fl5_swap_mini: "Kalimatku",
    fl5_btn_speak_swap: "Ucapkan seperti ini",
    fl5_btn_listen_swap: "Dengarkan seperti ini",
    fl5_spoken_count: "{n} / 3 kali berbicara",
    fl5_over_done: "STEP 5 · SELESAI",
    fl5_badge_first_done: "Berhasil! 🎉",
    fl5_result_title: "Berhasil! 🎉",
    fl5_rs_you_said: "Yang saya ucapkan",
    fl5_rs_model: "Jawaban model",
    fl5_apply_section: "Kamu juga bisa berkata...",
    fl5_apply_hint: "Coba ganti bagian kosong dengan kata-kata ini:",
    fl5_rs_vocab: "Kosakata",
    fl5_stat_times: "Kali berbicara",
    fl5_stat_streak: "Hari berturut",
    fl5_btn_next_day: "Mulai Hari {n} →",
    fl5_btn_retry_swap: "Coba lagi",
    fl5_btn_home_go: "Ke beranda",
    fl5_rs_eval_perfect: "Sempurna!",
    fl5_rs_eval_good: "Bagus!",
    fl5_rs_eval_keep: "Terus coba!",
    fl5_day_done_title: "Hari {n} selesai!",
    fl5_day_done_sub: "Kamu berbicara bahasa Korea hari ini",
    fl5_recall_hidden: "Kalimat tersembunyi — gunakan petunjuk pelafalan.",
    fl5_btn_retry_speak: "Ketuk untuk bicara lagi",
    fl5_btn_mic_prepare: "Bersiap...",
    fl5_btn_mic_listening: "Mendengarkan...",
    fl5_mic_hint_idle_repeat: "Ketuk tombol dan ucapkan kalimat di atas",
    fl5_mic_hint_idle_recall: "Ketuk tombol dan ucapkan dari ingatan",
    fl5_mic_hint_listening: "Terus bicara... Aku mendengarkan 👂",
    fl5_mic_hint_done: "Selesai! Ketuk lanjut jika siap",
    fl5_stt_empty: "Kami tidak menangkap suara. Coba lagi!",
    fl5_onboard_step: "Step {n} of 3",
    fl5_onboard_1: "Pertama, dengarkan kalimat 3 kali. Ketuk tombol Listen!",
    fl5_onboard_2: "Ketuk setiap kata untuk mendengar bunyinya.",
    fl5_onboard_3: "Sekarang ketuk 'Tap to speak' dan ucapkan kalimatnya!",
    fl5_onboard_cta: "Mengerti →",
    fl5_onboard_start: "Mulai!",
    fl_pre_tooltip_step: "Langkah {n} dari 3",
    fl_pre_tooltip_1: "Dengarkan kalimat 3 kali sebelum berbicara",
    fl_pre_tooltip_2: "Ketuk setiap kata untuk mendengar bunyinya",
    fl_pre_tooltip_3: "Ketuk 'Tap to speak' dan ucapkan kalimatnya keras-keras!",
    fl_pre_tooltip_start: "Let's start! →",
    fl_browser_not_supported_title: "Suara tidak tersedia di browser ini",
    fl_browser_not_supported_desc: "Buka Kkobi di Chrome untuk pengalaman berbicara penuh.",
    fl_open_in_chrome: "Buka di Chrome",
    fl_browser_not_supported_hint: "Salin tautan dan tempel di Chrome jika tombol tidak berfungsi.",
    fl_mic_permission_title: "Akses mikrofon ditolak",
    fl_mic_permission_desc: "Izinkan akses mikrofon di pengaturan browser dan coba lagi.",
    fl_stt_try_again: "Coba lagi",
    fl_stt_no_speech_hint: "Kami tidak mendengar apapun. Bicaralah dengan jelas dan coba lagi!",
    fl_stt_network_error_hint: "Kesalahan jaringan. Periksa koneksi dan coba lagi.",
    fl_stt_generic_error: "Input suara bermasalah. Silakan coba lagi.",
    fl_chrome_recommended: "Untuk pengalaman terbaik, buka di browser Chrome.",
    fl_stt_try_anyway: "Coba bicara saja"
  },
  fr: {
    fl5_over_listen: "STEP 1 · ÉCOUTER",
    fl5_over_understand: "STEP 2 · VOCABULAIRE",
    fl5_over_repeat: "STEP 3 · RÉPÉTER",
    fl5_over_recall: "STEP 4 · RAPPEL",
    fl5_over_swap: "STEP 5 · ÉCHANGER",
    fl5_hero_today: "Phrase du jour",
    fl5_btn_listen: "Écouter",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Écouter lentement",
    fl5_next_vocab: "Apprends les mots",
    fl5_situation_when: "Quand l’utiliser ?",
    fl5_words_hint: "Touche un mot pour l’entendre",
    fl5_repeat_hint: "Répète ce que tu entends",
    fl5_btn_listen_again: "Écouter encore",
    fl5_btn_speak_now: "Parle maintenant",
    fl5_btn_speaking: "Écoute…",
    fl5_btn_follow_speak: "Appuyez pour parler",
    fl5_btn_follow_speaking: "Répétition…",
    fl5_next_repeat: "Dis la phrase",
    fl5_next_recall: "Maintenant dites-le vous-même",
    fl5_recall_hint: "Phrase masquée — dis-la de mémoire !",
    fl5_recall_line1: "La phrase est masquée.",
    fl5_recall_line2: "Dites-la de mémoire !",
    fl5_roman_hint: "Indice de prononciation",
    fl5_btn_speak_practice: "Appuyez pour parler",
    fl5_next_swap: "Rends-la tienne",
    fl5_next_result: "Voir mon résultat",
    fl5_you_said: "Ce que tu as dit",
    fl5_swap_pick: "Choisis un mot pour ta phrase",
    fl5_swap_mini: "Ma phrase",
    fl5_btn_speak_swap: "Parle ainsi",
    fl5_btn_listen_swap: "Écoute ainsi",
    fl5_spoken_count: "{n} / 3 fois",
    fl5_over_done: "STEP 5 · TERMINÉ",
    fl5_badge_first_done: "Vous l'avez fait! 🎉",
    fl5_result_title: "Vous l'avez fait! 🎉",
    fl5_rs_you_said: "Ce que j’ai dit",
    fl5_rs_model: "Réponse modèle",
    fl5_apply_section: "Vous pouvez aussi dire...",
    fl5_apply_hint: "Essayez de remplacer le blanc par ces mots:",
    fl5_rs_vocab: "Vocabulaire",
    fl5_stat_times: "Fois parlé",
    fl5_stat_streak: "Jours consécutifs",
    fl5_btn_next_day: "Commencer le jour {n} →",
    fl5_btn_retry_swap: "Réessayer",
    fl5_btn_home_go: "Accueil",
    fl5_rs_eval_perfect: "Parfait!",
    fl5_rs_eval_good: "Bien essayé!",
    fl5_rs_eval_keep: "Continuez!",
    fl5_day_done_title: "Jour {n} terminé !",
    fl5_day_done_sub: "Vous avez parlé coréen aujourd'hui",
    fl5_recall_hidden: "Phrase masquée — utilise l’indice de prononciation.",
    fl5_btn_retry_speak: "Appuyez pour reparler",
    fl5_btn_mic_prepare: "Prêt...",
    fl5_btn_mic_listening: "J'écoute...",
    fl5_mic_hint_idle_repeat: "Touche le bouton et dis la phrase ci-dessus",
    fl5_mic_hint_idle_recall: "Touche le bouton et parle de mémoire",
    fl5_mic_hint_listening: "Continue de parler... J'écoute 👂",
    fl5_mic_hint_done: "Terminé ! Touche suivant quand tu es prêt",
    fl5_stt_empty: "On n'a pas bien entendu. Réessaie !",
    fl5_onboard_step: "Step {n} of 3",
    fl5_onboard_1: "D'abord, écoutez la phrase 3 fois. Appuyez sur Listen!",
    fl5_onboard_2: "Appuyez sur chaque mot pour entendre sa prononciation.",
    fl5_onboard_3: "Maintenant appuyez sur 'Tap to speak' et dites la phrase!",
    fl5_onboard_cta: "OK →",
    fl5_onboard_start: "C'est parti !",
    fl_pre_tooltip_step: "Étape {n} sur 3",
    fl_pre_tooltip_1: "Écoutez la phrase 3 fois avant de parler",
    fl_pre_tooltip_2: "Appuyez sur chaque mot pour entendre sa prononciation",
    fl_pre_tooltip_3: "Appuyez sur 'Tap to speak' et dites la phrase à voix haute!",
    fl_pre_tooltip_start: "Let's start! →",
    fl_browser_not_supported_title: "Voix non disponible dans ce navigateur",
    fl_browser_not_supported_desc: "Ouvrez Kkobi dans Chrome pour l'expérience vocale complète.",
    fl_open_in_chrome: "Ouvrir dans Chrome",
    fl_browser_not_supported_hint: "Copiez le lien et collez-le dans Chrome si le bouton ne fonctionne pas.",
    fl_mic_permission_title: "Accès au microphone refusé",
    fl_mic_permission_desc: "Autorisez l'accès au microphone dans les paramètres du navigateur et réessayez.",
    fl_stt_try_again: "Réessayer",
    fl_stt_no_speech_hint: "Nous n'avons rien entendu. Parlez clairement et réessayez!",
    fl_stt_network_error_hint: "Erreur réseau. Vérifiez votre connexion et réessayez.",
    fl_stt_generic_error: "Problème avec la saisie vocale. Réessaie.",
    fl_chrome_recommended: "Pour la meilleure expérience, ouvrez dans Chrome.",
    fl_stt_try_anyway: "Essayer quand même"
  },
  pt: {
    fl5_over_listen: "STEP 1 · OUVIR",
    fl5_over_understand: "STEP 2 · VOCABULÁRIO",
    fl5_over_repeat: "STEP 3 · REPETIR",
    fl5_over_recall: "STEP 4 · RECORDAR",
    fl5_over_swap: "STEP 5 · TROCAR",
    fl5_hero_today: "Frase de hoje",
    fl5_btn_listen: "Ouvir",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Ouvir devagar",
    fl5_next_vocab: "Aprenda as palavras",
    fl5_situation_when: "Quando usar?",
    fl5_words_hint: "Toque numa palavra para ouvir",
    fl5_repeat_hint: "Repita o que ouvir",
    fl5_btn_listen_again: "Ouvir novamente",
    fl5_btn_speak_now: "Falar agora",
    fl5_btn_speaking: "Ouvindo…",
    fl5_btn_follow_speak: "Toque para falar",
    fl5_btn_follow_speaking: "Repetindo…",
    fl5_next_repeat: "Diga a frase",
    fl5_next_recall: "Agora diga você mesmo",
    fl5_recall_hint: "Frase oculta — diga de memória!",
    fl5_recall_line1: "A frase está oculta.",
    fl5_recall_line2: "Diga de memória!",
    fl5_roman_hint: "Dica de pronúncia",
    fl5_btn_speak_practice: "Toque para falar",
    fl5_next_swap: "Torne sua",
    fl5_next_result: "Ver meu resultado",
    fl5_you_said: "O que você disse",
    fl5_swap_pick: "Escolha uma palavra para sua frase",
    fl5_swap_mini: "Minha frase",
    fl5_btn_speak_swap: "Fale assim",
    fl5_btn_listen_swap: "Ouça assim",
    fl5_spoken_count: "{n} / 3 vezes falado",
    fl5_over_done: "STEP 5 · FEITO",
    fl5_badge_first_done: "Você conseguiu! 🎉",
    fl5_result_title: "Você conseguiu! 🎉",
    fl5_rs_you_said: "O que eu disse",
    fl5_rs_model: "Resposta modelo",
    fl5_apply_section: "Você também pode dizer...",
    fl5_apply_hint: "Tente substituir o espaço em branco por estas palavras:",
    fl5_rs_vocab: "Vocabulário",
    fl5_stat_times: "Vezes falado",
    fl5_stat_streak: "Dias seguidos",
    fl5_btn_next_day: "Começar dia {n} →",
    fl5_btn_retry_swap: "Tentar novamente",
    fl5_btn_home_go: "Início",
    fl5_rs_eval_perfect: "Perfeito!",
    fl5_rs_eval_good: "Boa tentativa!",
    fl5_rs_eval_keep: "Continue!",
    fl5_day_done_title: "Dia {n} completo!",
    fl5_day_done_sub: "Você falou coreano hoje",
    fl5_recall_hidden: "Frase oculta — use a dica de pronúncia.",
    fl5_btn_retry_speak: "Toque para falar novamente",
    fl5_btn_mic_prepare: "Preparando...",
    fl5_btn_mic_listening: "Ouvindo...",
    fl5_mic_hint_idle_repeat: "Toque no botão e fale a frase acima",
    fl5_mic_hint_idle_recall: "Toque no botão e fale de memória",
    fl5_mic_hint_listening: "Continue falando... Estou ouvindo 👂",
    fl5_mic_hint_done: "Pronto! Toque em avançar quando quiser",
    fl5_stt_empty: "Não captamos o áudio. Tente de novo!",
    fl5_onboard_step: "Step {n} of 3",
    fl5_onboard_1: "Primeiro, ouça a frase 3 vezes. Toque em Listen!",
    fl5_onboard_2: "Toque em cada palavra para ouvir como soa.",
    fl5_onboard_3: "Agora toque em 'Tap to speak' e diga a frase em voz alta!",
    fl5_onboard_cta: "Entendi →",
    fl5_onboard_start: "Vamos lá!",
    fl_pre_tooltip_step: "Etapa {n} de 3",
    fl_pre_tooltip_1: "Ouça a frase 3 vezes antes de falar",
    fl_pre_tooltip_2: "Toque em cada palavra para ouvir como soa",
    fl_pre_tooltip_3: "Toque em 'Tap to speak' e diga a frase em voz alta!",
    fl_pre_tooltip_start: "Let's start! →",
    fl_browser_not_supported_title: "Voz não disponível neste navegador",
    fl_browser_not_supported_desc: "Abra o Kkobi no Chrome para a experiência de fala completa.",
    fl_open_in_chrome: "Abrir no Chrome",
    fl_browser_not_supported_hint: "Copie o link e cole no Chrome se o botão não funcionar.",
    fl_mic_permission_title: "Acesso ao microfone negado",
    fl_mic_permission_desc: "Permita o acesso ao microfone nas configurações do navegador e tente novamente.",
    fl_stt_try_again: "Tentar novamente",
    fl_stt_no_speech_hint: "Não ouvimos nada. Fale claramente e tente novamente!",
    fl_stt_network_error_hint: "Erro de rede. Verifique sua conexão e tente novamente.",
    fl_stt_generic_error: "Houve um problema na entrada de voz. Tente de novo.",
    fl_chrome_recommended: "Para a melhor experiência, abra no Chrome.",
    fl_stt_try_anyway: "Tentar falar assim mesmo"
  }
};
