/** First-line 5-step flow copy (merged into i18n STR). */
export const FL5_STR = {
  en: {
    fl5_over_listen: "DAY {n} · LISTEN FIRST",
    fl5_over_understand: "DAY {n} · UNDERSTAND",
    fl5_over_repeat: "DAY {n} · REPEAT AFTER ME",
    fl5_over_recall: "DAY {n} · SAY IT YOURSELF",
    fl5_over_swap: "DAY {n} · MAKE IT YOURS",
    fl5_hero_today: "Today's sentence",
    fl5_btn_listen: "Listen",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Listen slowly",
    fl5_next_vocab: "Learn the words",
    fl5_situation_when: "When do you use this?",
    fl5_words_hint: "Tap a word to hear it",
    fl5_repeat_hint: "Repeat what you hear",
    fl5_btn_listen_again: "Listen again",
    fl5_btn_speak_now: "Speak now",
    fl5_btn_speaking: "Listening…",
    fl5_next_repeat: "Say the sentence",
    fl5_next_recall: "Say it yourself",
    fl5_recall_hint: "The sentence is hidden. Say it from memory!",
    fl5_roman_hint: "Pronunciation hint",
    fl5_btn_speak_practice: "Speak",
    fl5_next_swap: "Make it yours",
    fl5_you_said: "What you said",
    fl5_swap_pick: "Pick a word to make your sentence",
    fl5_swap_mini: "My sentence",
    fl5_btn_speak_swap: "Speak like this",
    fl5_btn_listen_swap: "Listen like this",
    fl5_spoken_count: "{n} / 3 times spoken",
    fl5_over_done: "DAY {n} · DONE",
    fl5_badge_first_done: "First line complete",
    fl5_result_title: "Day {n} complete! 🎉",
    fl5_rs_you_said: "What I said",
    fl5_rs_model: "Model answer",
    fl5_rs_vocab: "Vocabulary",
    fl5_stat_times: "Times spoken",
    fl5_stat_streak: "Day streak",
    fl5_btn_next_day: "Start Day {n} →",
    fl5_btn_retry_swap: "Try again",
    fl5_btn_home_go: "Go to home",
    fl5_rs_eval_perfect: "Perfect!",
    fl5_rs_eval_good: "Practice a bit more!",
    fl5_rs_eval_keep: "Try once more!",
    fl5_day_done_title: "Day {n} complete!",
    fl5_day_done_sub: "You spoke Korean today.",
    fl5_recall_hidden: "Sentence hidden — use the pronunciation hint.",
    fl5_btn_retry_speak: "Try again"
  },
  ko: {
    fl5_over_listen: "DAY {n} · 먼저 듣기",
    fl5_over_understand: "DAY {n} · 의미 이해",
    fl5_over_repeat: "DAY {n} · 따라 말하기",
    fl5_over_recall: "DAY {n} · 스스로 말하기",
    fl5_over_swap: "DAY {n} · 바꿔 말하기",
    fl5_hero_today: "오늘의 문장",
    fl5_btn_listen: "들어보기",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "천천히 듣기",
    fl5_next_vocab: "이제 단어를 배워요",
    fl5_situation_when: "언제 쓰는 표현?",
    fl5_words_hint: "단어를 눌러 들어보세요",
    fl5_repeat_hint: "들리는 대로 따라 말해보세요",
    fl5_btn_listen_again: "다시 듣기",
    fl5_btn_speak_now: "지금 말해보기",
    fl5_btn_speaking: "지금 말하는 중...",
    fl5_next_repeat: "이제 문장을 말해요",
    fl5_next_recall: "이제 직접 말해요",
    fl5_recall_hint: "문장을 가렸어요. 기억해서 말해보세요!",
    fl5_roman_hint: "발음 힌트",
    fl5_btn_speak_practice: "말해보기",
    fl5_next_swap: "이제 바꿔서 말해요",
    fl5_you_said: "내가 말한 것",
    fl5_swap_pick: "단어를 골라 내 문장을 만들어보세요",
    fl5_swap_mini: "내 문장",
    fl5_btn_speak_swap: "이렇게 말해보기",
    fl5_btn_listen_swap: "이렇게 들어보기",
    fl5_spoken_count: "{n} / 3번 말했어요",
    fl5_over_done: "DAY {n} · 완료",
    fl5_badge_first_done: "첫 한마디 완료",
    fl5_result_title: "Day {n} 완료! 🎉",
    fl5_rs_you_said: "내가 말한 것",
    fl5_rs_model: "모범 답안",
    fl5_rs_vocab: "단어 보기",
    fl5_stat_times: "말한 횟수",
    fl5_stat_streak: "연속 학습일",
    fl5_btn_next_day: "Day {n} 시작하기 →",
    fl5_btn_retry_swap: "다시 말해보기",
    fl5_btn_home_go: "홈으로 가기",
    fl5_rs_eval_perfect: "완벽해요!",
    fl5_rs_eval_good: "조금 더 연습해요!",
    fl5_rs_eval_keep: "한 번 더 도전해요!",
    fl5_day_done_title: "Day {n} 완료!",
    fl5_day_done_sub: "오늘도 한국어로 말했어요",
    fl5_recall_hidden: "문장을 가렸어요. 발음 힌트만 보세요.",
    fl5_btn_retry_speak: "다시 말해보기"
  },
  id: {
    fl5_over_listen: "DAY {n} · DENGAR DULU",
    fl5_over_understand: "DAY {n} · PAHAMI",
    fl5_over_repeat: "DAY {n} · IKUTI AKU",
    fl5_over_recall: "DAY {n} · KATAKAN SENDIRI",
    fl5_over_swap: "DAY {n} · JADIKAN MILIKMU",
    fl5_hero_today: "Kalimat hari ini",
    fl5_btn_listen: "Dengarkan",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Dengar pelan",
    fl5_next_vocab: "Pelajari katanya",
    fl5_situation_when: "Kapan dipakai?",
    fl5_words_hint: "Ketuk kata untuk mendengar",
    fl5_repeat_hint: "Ulangi apa yang kamu dengar",
    fl5_btn_listen_again: "Dengar lagi",
    fl5_btn_speak_now: "Bicara sekarang",
    fl5_btn_speaking: "Mendengarkan…",
    fl5_next_repeat: "Ucapkan kalimatnya",
    fl5_next_recall: "Ucapkan sendiri",
    fl5_recall_hint: "Kalimat disembunyikan. Ucapkan dari ingatan!",
    fl5_roman_hint: "Petunjuk pelafalan",
    fl5_btn_speak_practice: "Bicara",
    fl5_next_swap: "Ubah kalimatmu",
    fl5_you_said: "Yang kamu katakan",
    fl5_swap_pick: "Pilih kata untuk kalimatmu",
    fl5_swap_mini: "Kalimatku",
    fl5_btn_speak_swap: "Ucapkan seperti ini",
    fl5_day_done_title: "Hari {n} selesai!",
    fl5_day_done_sub: "Kamu berbicara bahasa Korea hari ini.",
    fl5_recall_hidden: "Kalimat tersembunyi — gunakan petunjuk pelafalan.",
    fl5_btn_retry_speak: "Coba lagi"
  },
  fr: {
    fl5_over_listen: "DAY {n} · ÉCOUTER D’ABORD",
    fl5_over_understand: "DAY {n} · COMPRENDRE",
    fl5_over_repeat: "DAY {n} · RÉPÈTE",
    fl5_over_recall: "DAY {n} · DIS LE TOI-MÊME",
    fl5_over_swap: "DAY {n} · À TA FAÇON",
    fl5_hero_today: "Phrase du jour",
    fl5_btn_listen: "Écouter",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Écouter lentement",
    fl5_next_vocab: "Apprends les mots",
    fl5_situation_when: "Quand l’utiliser ?",
    fl5_words_hint: "Touche un mot pour l’entendre",
    fl5_repeat_hint: "Répète ce que tu entends",
    fl5_btn_listen_again: "Réécouter",
    fl5_btn_speak_now: "Parle maintenant",
    fl5_btn_speaking: "Écoute…",
    fl5_next_repeat: "Dis la phrase",
    fl5_next_recall: "Dis-le toi-même",
    fl5_recall_hint: "Phrase masquée — dis-la de mémoire !",
    fl5_roman_hint: "Indice de prononciation",
    fl5_btn_speak_practice: "Parler",
    fl5_next_swap: "Rends-la tienne",
    fl5_you_said: "Ce que tu as dit",
    fl5_swap_pick: "Choisis un mot pour ta phrase",
    fl5_swap_mini: "Ma phrase",
    fl5_btn_speak_swap: "Dis-le ainsi",
    fl5_day_done_title: "Jour {n} terminé !",
    fl5_day_done_sub: "Tu as parlé coréen aujourd’hui.",
    fl5_recall_hidden: "Phrase masquée — utilise l’indice de prononciation.",
    fl5_btn_retry_speak: "Réessayer"
  },
  pt: {
    fl5_over_listen: "DAY {n} · OUVIR PRIMEIRO",
    fl5_over_understand: "DAY {n} · ENTENDER",
    fl5_over_repeat: "DAY {n} · REPITA COMIGO",
    fl5_over_recall: "DAY {n} · DIGA VOCÊ",
    fl5_over_swap: "DAY {n} · FAÇA SEU",
    fl5_hero_today: "Frase de hoje",
    fl5_btn_listen: "Ouvir",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Ouvir devagar",
    fl5_next_vocab: "Aprenda as palavras",
    fl5_situation_when: "Quando usar?",
    fl5_words_hint: "Toque numa palavra para ouvir",
    fl5_repeat_hint: "Repita o que ouvir",
    fl5_btn_listen_again: "Ouvir de novo",
    fl5_btn_speak_now: "Falar agora",
    fl5_btn_speaking: "Ouvindo…",
    fl5_next_repeat: "Diga a frase",
    fl5_next_recall: "Diga você mesmo",
    fl5_recall_hint: "Frase oculta — diga de memória!",
    fl5_roman_hint: "Dica de pronúncia",
    fl5_btn_speak_practice: "Falar",
    fl5_next_swap: "Torne sua",
    fl5_you_said: "O que você disse",
    fl5_swap_pick: "Escolha uma palavra para sua frase",
    fl5_swap_mini: "Minha frase",
    fl5_btn_speak_swap: "Fale assim",
    fl5_btn_listen_swap: "Ouça assim",
    fl5_spoken_count: "{n} / 3 vezes falado",
    fl5_over_done: "DAY {n} · FEITO",
    fl5_badge_first_done: "Primeira frase completa",
    fl5_result_title: "Dia {n} completo! 🎉",
    fl5_rs_you_said: "O que eu disse",
    fl5_rs_model: "Resposta modelo",
    fl5_rs_vocab: "Vocabulário",
    fl5_stat_times: "Vezes falado",
    fl5_stat_streak: "Dias seguidos",
    fl5_btn_next_day: "Começar dia {n} →",
    fl5_btn_retry_swap: "Tentar novamente",
    fl5_btn_home_go: "Ir para início",
    fl5_rs_eval_perfect: "Perfeito!",
    fl5_rs_eval_good: "Pratique um pouco mais!",
    fl5_rs_eval_keep: "Tente mais uma vez!",
    fl5_day_done_title: "Dia {n} completo!",
    fl5_day_done_sub: "Você falou coreano hoje.",
    fl5_recall_hidden: "Frase oculta — use a dica de pronúncia.",
    fl5_btn_retry_speak: "Tentar de novo"
  }
};
