/** First-line 5-step flow copy (merged into i18n STR). */
export const FL5_STR = {
  en: {
    fl5_over_listen: "STEP 1 · LISTEN",
    fl5_over_understand: "STEP 2 · VOCABULARY",
    fl5_over_repeat: "STEP 3 · REPEAT",
    fl5_over_recall: "STEP 4 · RECALL",
    fl5_over_swap: "STEP 5 · SWAP",
    fl5_hero_today: "Today's sentence",
    fl5_btn_listen: "Listen",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Listen slowly",
    fl5_next_vocab: "Learn the words",
    fl5_situation_when: "When do you use this?",
    fl5_words_hint: "Tap a word to hear it",
    fl5_repeat_hint: "Repeat what you hear",
    fl5_btn_listen_again: "Listen again",
    fl5_btn_speak_now: "Speak now",
    fl5_btn_speaking: "Listening…",
    fl5_btn_follow_speak: "Repeat after me",
    fl5_btn_follow_speaking: "Repeating…",
    fl5_next_repeat: "Say the sentence",
    fl5_next_recall: "Now say it yourself",
    fl5_recall_hint: "The sentence is hidden. Say it from memory!",
    fl5_recall_line1: "The sentence is hidden.",
    fl5_recall_line2: "Say it from memory!",
    fl5_roman_hint: "Pronunciation hint",
    fl5_btn_speak_practice: "Speak",
    fl5_next_swap: "Make it yours",
    fl5_next_result: "See my result",
    fl5_you_said: "What you said",
    fl5_swap_pick: "Pick a word to make your sentence",
    fl5_swap_mini: "My sentence",
    fl5_btn_speak_swap: "Speak like this",
    fl5_btn_listen_swap: "Listen like this",
    fl5_spoken_count: "{n} / 3 times spoken",
    fl5_over_done: "STEP 5 · DONE",
    fl5_badge_first_done: "You did it! 🎉",
    fl5_result_title: "You did it! 🎉",
    fl5_rs_you_said: "What I said",
    fl5_rs_model: "Model answer",
    fl5_apply_section: "You can also say...",
    fl5_apply_hint: "Try replacing the blank with these words:",
    fl5_rs_vocab: "Vocabulary",
    fl5_stat_times: "Times spoken",
    fl5_stat_streak: "Day streak",
    fl5_btn_next_day: "Start Day {n} →",
    fl5_btn_retry_swap: "Try again",
    fl5_btn_home_go: "Go to home",
    fl5_rs_eval_perfect: "Perfect!",
    fl5_rs_eval_good: "Good try!",
    fl5_rs_eval_keep: "Keep going!",
    fl5_day_done_title: "Day {n} complete!",
    fl5_day_done_sub: "You spoke Korean today",
    fl5_recall_hidden: "Sentence hidden — use the pronunciation hint.",
    fl5_btn_retry_speak: "Try again",
    fl5_btn_mic_prepare: "Get ready...",
    fl5_btn_mic_listening: "Listening...",
    fl5_mic_hint_idle_repeat: "Tap the button and speak the sentence above",
    fl5_mic_hint_idle_recall: "Tap the button and speak from memory",
    fl5_mic_hint_listening: "Keep speaking... I'm listening 👂",
    fl5_mic_hint_done: "Done! Tap next when ready",
    fl5_stt_empty: "We couldn't catch that. Try again!",
    fl5_onboard_1: "👆 First, listen to the sentence 3 times",
    fl5_onboard_2: "📖 Learn each word by tapping it",
    fl5_onboard_3: "🎤 Then repeat after the audio!",
    fl5_onboard_cta: "Got it →",
    fl5_onboard_start: "Let's start!"
  },
  id: {
    fl5_over_listen: "STEP 1 · DENGAR",
    fl5_over_understand: "STEP 2 · KOSAKATA",
    fl5_over_repeat: "STEP 3 · ULANG",
    fl5_over_recall: "STEP 4 · UCAP SENDIRI",
    fl5_over_swap: "STEP 5 · UBAH",
    fl5_hero_today: "Kalimat hari ini",
    fl5_btn_listen: "Dengarkan",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Dengarkan perlahan",
    fl5_next_vocab: "Pelajari katanya",
    fl5_situation_when: "Kapan dipakai?",
    fl5_words_hint: "Ketuk kata untuk mendengar",
    fl5_repeat_hint: "Ulangi apa yang kamu dengar",
    fl5_btn_listen_again: "Dengarkan lagi",
    fl5_btn_speak_now: "Bicara sekarang",
    fl5_btn_speaking: "Mendengarkan…",
    fl5_btn_follow_speak: "Tirukan sekarang",
    fl5_btn_follow_speaking: "Sedang menirukan…",
    fl5_next_repeat: "Ucapkan kalimatnya",
    fl5_next_recall: "Sekarang ucapkan sendiri",
    fl5_recall_hint: "Kalimat disembunyikan. Ucapkan dari ingatan!",
    fl5_recall_line1: "Kalimat disembunyikan.",
    fl5_recall_line2: "Ucapkan dari ingatan!",
    fl5_roman_hint: "Petunjuk pelafalan",
    fl5_btn_speak_practice: "Bicara",
    fl5_next_swap: "Ubah kalimatmu",
    fl5_next_result: "Lihat hasil saya",
    fl5_you_said: "Yang kamu katakan",
    fl5_swap_pick: "Pilih kata untuk kalimatmu",
    fl5_swap_mini: "Kalimatku",
    fl5_btn_speak_swap: "Ucapkan seperti ini",
    fl5_btn_listen_swap: "Dengarkan seperti ini",
    fl5_spoken_count: "{n} / 3 kali berbicara",
    fl5_over_done: "STEP 5 · SELESAI",
    fl5_badge_first_done: "Berhasil! 🎉",
    fl5_result_title: "Berhasil! 🎉",
    fl5_rs_you_said: "Yang saya ucapkan",
    fl5_rs_model: "Jawaban model",
    fl5_apply_section: "Kamu juga bisa berkata...",
    fl5_apply_hint: "Coba ganti bagian kosong dengan kata-kata ini:",
    fl5_rs_vocab: "Kosakata",
    fl5_stat_times: "Kali berbicara",
    fl5_stat_streak: "Hari berturut",
    fl5_btn_next_day: "Mulai Hari {n} →",
    fl5_btn_retry_swap: "Coba lagi",
    fl5_btn_home_go: "Ke beranda",
    fl5_rs_eval_perfect: "Sempurna!",
    fl5_rs_eval_good: "Bagus!",
    fl5_rs_eval_keep: "Terus coba!",
    fl5_day_done_title: "Hari {n} selesai!",
    fl5_day_done_sub: "Kamu berbicara bahasa Korea hari ini",
    fl5_recall_hidden: "Kalimat tersembunyi — gunakan petunjuk pelafalan.",
    fl5_btn_retry_speak: "Coba lagi",
    fl5_btn_mic_prepare: "Bersiap...",
    fl5_btn_mic_listening: "Mendengarkan...",
    fl5_mic_hint_idle_repeat: "Ketuk tombol dan ucapkan kalimat di atas",
    fl5_mic_hint_idle_recall: "Ketuk tombol dan ucapkan dari ingatan",
    fl5_mic_hint_listening: "Terus bicara... Aku mendengarkan 👂",
    fl5_mic_hint_done: "Selesai! Ketuk lanjut jika siap",
    fl5_stt_empty: "Kami tidak menangkap suara. Coba lagi!",
    fl5_onboard_1: "Pertama, dengarkan kalimat 3 kali",
    fl5_onboard_2: "Pelajari setiap kata dengan mengetuknya",
    fl5_onboard_3: "Lalu tirukan audionya!",
    fl5_onboard_cta: "Mengerti →",
    fl5_onboard_start: "Mulai!"
  },
  fr: {
    fl5_over_listen: "STEP 1 · ÉCOUTER",
    fl5_over_understand: "STEP 2 · VOCABULAIRE",
    fl5_over_repeat: "STEP 3 · RÉPÉTER",
    fl5_over_recall: "STEP 4 · RAPPEL",
    fl5_over_swap: "STEP 5 · ÉCHANGER",
    fl5_hero_today: "Phrase du jour",
    fl5_btn_listen: "Écouter",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Écouter lentement",
    fl5_next_vocab: "Apprends les mots",
    fl5_situation_when: "Quand l’utiliser ?",
    fl5_words_hint: "Touche un mot pour l’entendre",
    fl5_repeat_hint: "Répète ce que tu entends",
    fl5_btn_listen_again: "Écouter encore",
    fl5_btn_speak_now: "Parle maintenant",
    fl5_btn_speaking: "Écoute…",
    fl5_btn_follow_speak: "Répète après moi",
    fl5_btn_follow_speaking: "Répétition…",
    fl5_next_repeat: "Dis la phrase",
    fl5_next_recall: "Maintenant dites-le vous-même",
    fl5_recall_hint: "Phrase masquée — dis-la de mémoire !",
    fl5_recall_line1: "La phrase est masquée.",
    fl5_recall_line2: "Dites-la de mémoire !",
    fl5_roman_hint: "Indice de prononciation",
    fl5_btn_speak_practice: "Parler",
    fl5_next_swap: "Rends-la tienne",
    fl5_next_result: "Voir mon résultat",
    fl5_you_said: "Ce que tu as dit",
    fl5_swap_pick: "Choisis un mot pour ta phrase",
    fl5_swap_mini: "Ma phrase",
    fl5_btn_speak_swap: "Parle ainsi",
    fl5_btn_listen_swap: "Écoute ainsi",
    fl5_spoken_count: "{n} / 3 fois",
    fl5_over_done: "STEP 5 · TERMINÉ",
    fl5_badge_first_done: "Vous l'avez fait! 🎉",
    fl5_result_title: "Vous l'avez fait! 🎉",
    fl5_rs_you_said: "Ce que j’ai dit",
    fl5_rs_model: "Réponse modèle",
    fl5_apply_section: "Vous pouvez aussi dire...",
    fl5_apply_hint: "Essayez de remplacer le blanc par ces mots:",
    fl5_rs_vocab: "Vocabulaire",
    fl5_stat_times: "Fois parlé",
    fl5_stat_streak: "Jours consécutifs",
    fl5_btn_next_day: "Commencer le jour {n} →",
    fl5_btn_retry_swap: "Réessayer",
    fl5_btn_home_go: "Accueil",
    fl5_rs_eval_perfect: "Parfait!",
    fl5_rs_eval_good: "Bien essayé!",
    fl5_rs_eval_keep: "Continuez!",
    fl5_day_done_title: "Jour {n} terminé !",
    fl5_day_done_sub: "Vous avez parlé coréen aujourd'hui",
    fl5_recall_hidden: "Phrase masquée — utilise l’indice de prononciation.",
    fl5_btn_retry_speak: "Réessayer",
    fl5_btn_mic_prepare: "Prêt...",
    fl5_btn_mic_listening: "J'écoute...",
    fl5_mic_hint_idle_repeat: "Touche le bouton et dis la phrase ci-dessus",
    fl5_mic_hint_idle_recall: "Touche le bouton et parle de mémoire",
    fl5_mic_hint_listening: "Continue de parler... J'écoute 👂",
    fl5_mic_hint_done: "Terminé ! Touche suivant quand tu es prêt",
    fl5_stt_empty: "On n'a pas bien entendu. Réessaie !",
    fl5_onboard_1: "D'abord, écoutez la phrase 3 fois",
    fl5_onboard_2: "Apprenez chaque mot en appuyant dessus",
    fl5_onboard_3: "Puis répétez après l'audio !",
    fl5_onboard_cta: "OK →",
    fl5_onboard_start: "C'est parti !"
  },
  pt: {
    fl5_over_listen: "STEP 1 · OUVIR",
    fl5_over_understand: "STEP 2 · VOCABULÁRIO",
    fl5_over_repeat: "STEP 3 · REPETIR",
    fl5_over_recall: "STEP 4 · RECORDAR",
    fl5_over_swap: "STEP 5 · TROCAR",
    fl5_hero_today: "Frase de hoje",
    fl5_btn_listen: "Ouvir",
    fl5_listen_count: "{n}/3",
    fl5_btn_slow: "Ouvir devagar",
    fl5_next_vocab: "Aprenda as palavras",
    fl5_situation_when: "Quando usar?",
    fl5_words_hint: "Toque numa palavra para ouvir",
    fl5_repeat_hint: "Repita o que ouvir",
    fl5_btn_listen_again: "Ouvir novamente",
    fl5_btn_speak_now: "Falar agora",
    fl5_btn_speaking: "Ouvindo…",
    fl5_btn_follow_speak: "Repita depois de mim",
    fl5_btn_follow_speaking: "Repetindo…",
    fl5_next_repeat: "Diga a frase",
    fl5_next_recall: "Agora diga você mesmo",
    fl5_recall_hint: "Frase oculta — diga de memória!",
    fl5_recall_line1: "A frase está oculta.",
    fl5_recall_line2: "Diga de memória!",
    fl5_roman_hint: "Dica de pronúncia",
    fl5_btn_speak_practice: "Falar",
    fl5_next_swap: "Torne sua",
    fl5_next_result: "Ver meu resultado",
    fl5_you_said: "O que você disse",
    fl5_swap_pick: "Escolha uma palavra para sua frase",
    fl5_swap_mini: "Minha frase",
    fl5_btn_speak_swap: "Fale assim",
    fl5_btn_listen_swap: "Ouça assim",
    fl5_spoken_count: "{n} / 3 vezes falado",
    fl5_over_done: "STEP 5 · FEITO",
    fl5_badge_first_done: "Você conseguiu! 🎉",
    fl5_result_title: "Você conseguiu! 🎉",
    fl5_rs_you_said: "O que eu disse",
    fl5_rs_model: "Resposta modelo",
    fl5_apply_section: "Você também pode dizer...",
    fl5_apply_hint: "Tente substituir o espaço em branco por estas palavras:",
    fl5_rs_vocab: "Vocabulário",
    fl5_stat_times: "Vezes falado",
    fl5_stat_streak: "Dias seguidos",
    fl5_btn_next_day: "Começar dia {n} →",
    fl5_btn_retry_swap: "Tentar novamente",
    fl5_btn_home_go: "Início",
    fl5_rs_eval_perfect: "Perfeito!",
    fl5_rs_eval_good: "Boa tentativa!",
    fl5_rs_eval_keep: "Continue!",
    fl5_day_done_title: "Dia {n} completo!",
    fl5_day_done_sub: "Você falou coreano hoje",
    fl5_recall_hidden: "Frase oculta — use a dica de pronúncia.",
    fl5_btn_retry_speak: "Tentar de novo",
    fl5_btn_mic_prepare: "Preparando...",
    fl5_btn_mic_listening: "Ouvindo...",
    fl5_mic_hint_idle_repeat: "Toque no botão e fale a frase acima",
    fl5_mic_hint_idle_recall: "Toque no botão e fale de memória",
    fl5_mic_hint_listening: "Continue falando... Estou ouvindo 👂",
    fl5_mic_hint_done: "Pronto! Toque em avançar quando quiser",
    fl5_stt_empty: "Não captamos o áudio. Tente de novo!",
    fl5_onboard_1: "Primeiro, ouça a frase 3 vezes",
    fl5_onboard_2: "Aprenda cada palavra tocando nela",
    fl5_onboard_3: "Depois repita após o áudio!",
    fl5_onboard_cta: "Entendi →",
    fl5_onboard_start: "Vamos lá!"
  }
};
